
name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Command
        env:
          CICD_TOKEN: ${{ secrets.CICD }}
        run: |
          yarn
          (yarn dev) & (sleep 10 && yarn docs:dev) & (sleep 25 && yarn docs:build)
          cd docs/.vuepress/dist
          git config --global user.name  "github action"
          git config --global user.email "karanijohn018@gmail.com"
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://${GITHUB_ACTOR}:${CICD_TOKEN}@github.com/karani12/karani12.github.io master:gh-pages